name: Export LeetCode Submissions

on:
  workflow_dispatch:  # Manual trigger

jobs:
  leetcode-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run LeetCode Exporter
        uses: shihyuho/leetcode-export-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          leetcode_csrf_token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
