name: Test LeetCode Export (Single Problem)

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install leetcode-cli
        run: npm install -g leetcode-cli

      - name: Login to LeetCode
        run: leetcode user -l -s ${{ secrets.LEETCODE_SESSION }}

      - name: Test export of 1 problem (reverse-linked-list)
        run: |
          mkdir -p submissions
          leetcode show reverse-linked-list -l python3 -g -o submissions
          echo "🗂 Saved files:"
          ls -lh submissions

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add submissions || echo "Nothing to add"
          git commit -m "Add test export: reverse-linked-list" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
