name: Export LeetCode Submissions

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install leetcode-cli
        run: npm install -g leetcode-cli

      - name: Configure LeetCode Session
        run: leetcode user -l -s ${{ secrets.LEETCODE_SESSION }}

      - name: Fetch all accepted problems
        run: |
          mkdir -p submissions
          cd submissions
          leetcode list -q --ac > accepted.txt
          count=0
          for slug in $(cut -f3 -d',' accepted.txt | tail -n +2); do
            echo "Fetching: $slug"
            leetcode show $slug -l python3 -g -o . && count=$((count + 1)) || echo "❌ Failed: $slug"
          done
          echo "✅ Exported $count problem(s)."
          echo "🗂 Listing saved files:"
          ls -lh *.py || echo "⚠️ No .py files found."

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Files
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add submissions || echo "Nothing to add"
          git commit -m "Add LeetCode submissions" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
