name: Export LeetCode Submissions

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install leetcode

      - name: Export LeetCode Problems
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: |
          mkdir -p leetcode_solutions
          cd leetcode_solutions
          leetcode user -l
          leetcode list -q --ac > list.txt
